### ISSUE TITLE
please provide Data set , download link is not working

### ISSUE THREAD

**Issue by varunraj14** [ChenglongChen/tensorflow-DSMM#1]
Hi , i am trying to download dataset from the link you provided but looks like the link is expired. I am trying to understand your code but data set format is confusing me , so please provide either the dataset or a sample dataset which is of same format.

Thanks in advance

**Comment by ChenglongChen** [comment]
Hi, `./data` directory currently holds detailed description and also a toy dataset of the same format as in that competition. You can refer to that to prepare your input dataset accordingly. As for the download link, it is available after registration.

**Comment by qiuzhihong** [comment]
Hi, How to run the program with ‘toy dataset’？
It reports “FileNotFoundError: [Errno 2] No such file or directory: 'split.pkl'”

Thanks.
