### ISSUE TITLE
what does a split.pkl contain ??

### ISSUE THREAD

**Issue by varunraj14** [ChenglongChen/tensorflow-DSMM#2]

**Comment by ChenglongChen** [comment]
Hi,
You can see [here](https://github.com/ChenglongChen/tensorflow-DSMM/blob/master/src/main.py#L164). It is just a train & test split index. Usually, you can use [`train_test_split`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) from sklearn to generate them.
